#!/bin/bash

# Grove Cross-Platform Test Script
# Run this on macOS, Windows (WSL/Git Bash), or Linux to validate Grove

set -e

echo "=== Grove Platform Test Script ==="
echo ""

# Detect platform
case "$(uname -s)" in
    Linux*)     PLATFORM="Linux";;
    Darwin*)    PLATFORM="macOS";;
    CYGWIN*|MINGW*|MSYS*) PLATFORM="Windows";;
    *)          PLATFORM="Unknown";;
esac

echo "Platform: $PLATFORM"
echo "Architecture: $(uname -m)"
echo ""

# Check for Zig
if ! command -v zig &> /dev/null; then
    echo "❌ Zig is not installed or not in PATH"
    echo "Please install Zig from https://ziglang.org/download/"
    exit 1
fi

echo "✅ Zig found: $(zig version)"

# Test basic build
echo ""
echo "Testing Grove build..."
if zig build; then
    echo "✅ Grove builds successfully on $PLATFORM"
else
    echo "❌ Grove build failed on $PLATFORM"
    exit 1
fi

# Test cross-platform validation
echo ""
echo "Running cross-platform validation suite..."
if zig build cross-platform; then
    echo "✅ Cross-platform validation passed on $PLATFORM"
else
    echo "❌ Cross-platform validation failed on $PLATFORM"
    exit 1
fi

# Test specific tools
echo ""
echo "Testing Grove tools..."

# Test Grim configuration export
if zig build grim-config -- config > /dev/null; then
    echo "✅ Grim configuration export works"
else
    echo "❌ Grim configuration export failed"
fi

# Test benchmarks
if zig build bench > /dev/null; then
    echo "✅ Performance benchmarks work"
else
    echo "❌ Performance benchmarks failed"
fi

# Test incremental benchmarks
if zig build bench-incremental > /dev/null; then
    echo "✅ Incremental edit benchmarks work"
else
    echo "❌ Incremental edit benchmarks failed"
fi

# Run tests
echo ""
echo "Running test suite..."
if zig build test; then
    echo "✅ All tests passed on $PLATFORM"
else
    echo "❌ Some tests failed on $PLATFORM"
    exit 1
fi

echo ""
echo "🎉 All tests passed! Grove is working correctly on $PLATFORM"

# Generate platform report
REPORT_DIR="validation_reports"
mkdir -p "$REPORT_DIR"

REPORT_FILE="$REPORT_DIR/platform_test_${PLATFORM}_$(date +%Y%m%d_%H%M%S).md"

cat > "$REPORT_FILE" << EOF
# Grove Platform Test Report

**Platform**: $PLATFORM
**Architecture**: $(uname -m)
**Date**: $(date)
**Zig Version**: $(zig version)

## Test Results

✅ **Build Test**: Passed
✅ **Cross-Platform Validation**: Passed
✅ **Grim Configuration Export**: Passed
✅ **Performance Benchmarks**: Passed
✅ **Incremental Edit Benchmarks**: Passed
✅ **Unit Tests**: Passed

## Conclusion

Grove is fully functional on $PLATFORM with all core features working correctly.

Generated by: scripts/test_platform.sh
EOF

echo "📄 Platform test report saved: $REPORT_FILE"