name: Grove CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-core:
    name: Test Grove Core
    runs-on: [self-hosted, nvidia, gpu, zig, palladium]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up tree-sitter dependencies
      run: |
        mkdir -p vendor/tree-sitter/lib/include/tree_sitter vendor/tree-sitter/lib/src

        # Download and extract tree-sitter v0.22.6
        curl -L https://github.com/tree-sitter/tree-sitter/archive/v0.22.6.tar.gz | tar xz
        cp -r tree-sitter-0.22.6/lib/* vendor/tree-sitter/lib/

        # Copy required headers to include directory
        cp tree-sitter-0.22.6/lib/include/tree_sitter/parser.h vendor/tree-sitter/lib/include/tree_sitter/
        cp tree-sitter-0.22.6/lib/src/alloc.h vendor/tree-sitter/lib/include/tree_sitter/

        # Clean up downloaded files
        rm -rf tree-sitter-0.22.6

    - name: Cache Zig dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/zig
          zig-cache
          zig-out
        key: ${{ runner.os }}-zig-${{ hashFiles('build.zig', 'build.zig.zon') }}
        restore-keys: |
          ${{ runner.os }}-zig-

    - name: Build Grove core
      run: zig build

    - name: Test tree-sitter parsing
      run: zig build test --filter "tree-sitter"

    - name: Test Ghostlang grammar
      run: zig build test --filter "ghostlang"

    - name: Run utility tests
      run: zig build test --filter "utilities"

    - name: Run all tests
      run: zig build test

    - name: Build benchmarks
      run: zig build bench

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ github.sha }}
        path: |
          zig-out/test/
          test-output.xml
        retention-days: 7